### ISSUE TITLE
Symbos Driver

### ISSUE THREAD

**Issue by jgilcas** [salafek/Net4CPC#1]
Hello.
Would it be possible to know which driver I have to load in symbos to make use of net4cpc?

Thanks for the impressive work.

**Comment by salafek** [comment]
I just uploaded it in the Extra folder together with a utility for setting the font/code-page in CP/M and a small font collection to play with.

**Comment by jgilcas** [comment]
Working!!!!!
![IMG_20230505_195016_137](https://user-images.githubusercontent.com/37148968/236533430-f5d69989-6eaf-4aeb-af21-8d08122a33e1.jpg)
